site_name: PeterPortal API Docs

repo_url: https://github.com/icssc-projects/peterportal-public-api
repo_name: icssc-projects/peterportal-public-api

theme:
  name: material
  custom_dir: overrides
  favicon: images/peter_favicon.png
  logo: images/peter_favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: indigo

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/

nav:
  - Home: index.md
  - Getting Started: 
    - Register: Getting-Started/Register-Here.md
    - Using Your API Key: Getting-Started/Using-Your-API-Key.md
  - REST API:
    - Start Here: REST-API/start_here.md
    - Courses: REST-API/courses.md
    - Instructors: REST-API/instructors.md
    - Grades: REST-API/grades.md
    - Schedule: REST-API/schedule.md
  - GraphQL API:
    - Start Here: GraphQL-API/start_here.md
  - Contributing: Contributing.md

extra_css:
  - css/termynal.css

extra_javascript:
  - js/termynal.js
  - js/forms.js
  - js/custom.js
