# serverless.yml
component: 
service: peterportal-api
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 512

package:
  patterns:
    - node_modules/**

plugins:
  - serverless-api-gateway-throttling
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies
  - serverless-domain-manager

custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 50
  includeDependencies:
    enableCaching: true
  customDomain: 
    domainName: api.peter-portal.com
    basepath: ""
    certificateName: "*.peter-portal.com"
    createRoute53Record: true
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    certificateArn: ${env:AWS_CERT_ARN}
    

functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY