# serverless.yml
component: 
service: peterportal-api
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev
  timeout: 15
  memorySize: 512
  logRetentionInDays: 30
  apiGateway:
    binaryMediaTypes:
      - 'image/*'
package:
  patterns:
    - node_modules/**

plugins:
  - serverless-api-gateway-throttling
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies
  # - serverless-domain-manager
  - serverless-plugin-lambda-insights
  - serverless-api-gateway-caching

custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 3600
    dataEncrypted: true
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 50
  includeDependencies:
    enableCaching: true
  # customDomain: 
  #   domainName: api.peterportal.org
  #   basepath: ""
  #   certificateName: "*.peterportal.org"
  #   createRoute53Record: true
  #   stage: ${self:provider.stage}
  lambdaInsights:
    defaultLambdaInsights: true #enables Lambda Insights for all functions

functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          integration: lambda
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.proxy
              - name: integration.request.header.bodyValue
                mappedFrom: method.request.body
      - http: 
          path: /{proxy+}
          method: ANY
          integration: lambda
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.proxy
              - name: integration.request.header.bodyValue
                mappedFrom: method.request.body