# serverless.yml

service: my-express-application
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-api-gateway-throttling
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 20
    maxConcurrentRequests: 50
  includeDependencies:
    enableCaching: true
    

functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY