version: 2.1

workflows: 
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
              - serverless-test

jobs:
  build:
    docker:
      - image: circleci/node:12.22
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g --unsafe-perm serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Deploy application
          command: sls deploy --stage prod