name: build docs
on:
  push:
    branches:
      - docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build MkDocs site
        run: |
          pip install mkdocs-material
          mkdocs build -d docs-site

#      - name: push build
